In [4]:
varibale="pavan"
print(varibale)
type(varibale)

pavan


str

In [5]:
a=10
type(a)


int

In [4]:
b = 26.6
type(b)
int(b)

26

In [6]:
print(4*5)

20


In [10]:
a="4"
b="5"
print(a + " "+ b)

4 5


In [15]:
a=4
b="5"
print(a+int(b))

9


In [12]:
b="2345"

# b="pavan"

b=int(b)
type(b)

int

In [22]:
a=int(input())
b=int(input())
print(a*b)

 10
 15


150


In [26]:
a=input()

 10


In [29]:
a=5
print(float(a))
a=float(a)
type(a)


5.0


float

In [30]:
int()
str()
float()

0.0

In [32]:
# indexing

In [72]:
0,1,2,3,4,5
a="hello world india"
a=a.split(" ")
a


['hello', 'world', 'india']

In [34]:
a="Hello World"
l=list(a)
print(l)

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']


In [42]:
list=[1,"pavan"]

In [44]:
print(list[1])

pavan


In [64]:
list=[1,2,3,4,5,6,7]
print(list[-6])

2


In [65]:
l=['india','USA']
print(l[0])

india


In [1]:
s = "Geeks for Geeks"
a = list(s)
print(a)

['G', 'e', 'e', 'k', 's', ' ', 'f', 'o', 'r', ' ', 'G', 'e', 'e', 'k', 's']


In [2]:
a='Hello world'
l=list(a)
print(l)

['H', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']


In [3]:
print(l[4])

o


In [6]:
a="Hello World"
a=a.split(" ")
l=list(a)
print(l)

['Hello', 'World']


In [15]:
# If Else condition
a=11
if a>10:
    a=a+5
elif a<10:
    a=a-5
else:
    a=a-10

print(a)




16


In [18]:
a=21
b=16
if a>20:
    if b<15:
        print('true')
    else:
        print('no')
else:
    print('No')
    
    

no


In [ ]:
lists
# slicing
# how to use if else with lists
# append
mapping
# sets
# and 
# or
# sorted

In [22]:
print(5//3)

1


In [23]:
a=10
if a%2==0:
    print('Even')
else:
    print('Odd')

Even


In [25]:
print(round(5/3,3))

1.667


In [ ]:
write a program to tell that the number is a amstrong number or not
153= 1**3+5**3+3**3

In [7]:
a=int(input())
b=(int(str(a)[0])**3)+(int(str(a)[1])**3)+(int(str(a)[2])**3)
type(a)

 121


int

In [11]:
print("paban","pavan",sep='\n')


paban
pavan


In [15]:
print("pavan",end="")
print("kumar",end="")
print("mamidi")

pavankumarmamidi


In [22]:
a=int(input())
list=[1,2,3,4,5,6]
if a not in list:
    print("no")
else:
    print("yes")

 7


no


In [25]:
a="PAVAN"
print(a.lower())

pavan


In [27]:
a=int(input())
if a>30 or a<40:
    print("ok")
elif a<30:
    print("yes")
else:
    print("no")

 41


ok


In [36]:
list=[1,2,3,4,5]
for i in list:
    print(f"{i}-{list.index(i)}")


1-0
2-1
3-2
4-3
5-4
pavan[1, 2, 3, 4, 5]dhfndsa


In [29]:
print(list)

[1, 2, 3, 4, 5, 6]


In [37]:
list=[1,2,3,4,5]
list.insert(1,7)

In [38]:
print(list)

[1, 7, 2, 3, 4, 5]


In [74]:
list=[1,3,42,2,0,5,4,2]
list.sort(reverse=True)
print(list)



[42, 5, 4, 3, 2, 2, 1, 0]


In [76]:
print(list)

[42, 5, 4, 3, 2, 2, 1, 0]


In [ ]:
dictionaries
# forloop
while loop
# bitwise 
# or
# nor
# xor
# remove duplicates
# print the duplicates
# update in lists
# remove from lists


In [78]:
s={1,2,3,4,5}
a=list(s)
print(a)
print(type(s))

TypeError: 'list' object is not callable

In [54]:
s

TypeError: 'set' object is not subscriptable

In [80]:
s={1,2,3,4,5}
a=list(s)
print(a)

TypeError: 'list' object is not callable

In [14]:
a=list(map(str,input().split(" ")))
print(a)
a.sort(reverse=True)
a
print(a)

KeyboardInterrupt: Interrupted by user

In [1]:
l=[100,2000,4000,40]

In [3]:
10= 0000 1010
11= 0000 1011
    0000 1011

11


In [6]:
print(11)

1


In [7]:
print(10<<2)

40


In [8]:
# 0000 1010
# 00



SyntaxError: invalid syntax (1539189614.py, line 1)

In [17]:
l=[1,2,3,4,5]
l.update(2)

AttributeError: 'list' object has no attribute 'update'

In [18]:
print(l)

[1, 2, 3, 4, 5]


In [19]:
l[0]=2

In [20]:
print(l)

[2, 2, 3, 4, 5]


In [21]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [20]:
l=[2,3,4,2,3,4]
sum1=0
for i in range(len(l)):
    sum1=sum1+l[i]
print(sum1)
print(sum(l))

18
18


In [2]:
print(sum1)

18


In [3]:
print(sum(l))

18


In [4]:
l=[1,2,3,4,5]
a=0
for i in l:
    a=a+i
print(a)

15


In [22]:
l=[1,2,2,3,4,5,6,6]
for i in l:
    if l.count(i)>1:
        print(i)

2
2
6
6


In [24]:
l=[1,2,3,4,4,3,1,5]
k=[]
for i in l:
    if i not in k:
        k.append(i)
print(k)


[1, 2, 3, 4, 5]


In [10]:
print(k)

[1]


In [11]:
type(k)

list

In [14]:
import math

In [ ]:
print(math.pow(3,2))

In [ ]:
*
**
***
****
*****
******
*******

In [ ]:
break
continue
pass

In [3]:
n=int(input())
while n<=10:
    print(n)
    n=n+1

 1


1
2
3
4
5
6
7
8
9
10


In [ ]:
n=int(input())
while n<=10:
    if n==5:
        continue
    print(n)
    n=n+1
    

In [ ]:
for i in range(1,11):
    if i==5:
        continue
    print(i)

In [6]:
i = 0
while i < 10:
    i += 1  # Increment first to avoid infinite loop
    if i % 2 == 0:
        continue  # Skip even numbers
    print(i)

1
3
5
7
9


In [3]:
n=int(input())
while n<10:
    n=n+1
    if n==5:
        pass
    print(n)

 2


3
4
5
6
7
8
9
10


In [4]:
l=[1,2,3,4,5]
n=0
while n<=len(l)-1:
    if l[n]%2!=0:
        print(l[n])
    n=n+1

1
3
5


In [1]:
n=int(input())
a=0
b=1
print(a)
print(b)
for i in range(n-1):
    c=a+b
    print(c)
    a=b
    b=c
    

 10


0
1
1
2
3
5
8
13
21
34
55


In [ ]:
a=0
b=1

c=a+b
print(c)
a=b
b=c

0 1 1 2
    a b c

In [3]:
# functions
a=5
b=6
print(a+b)

11


In [ ]:
def finction_name():
    return b

In [10]:
def sum_1():
    a=1
    b=2
    pass

sum_1()

In [5]:
sum_1()

3

In [11]:
def sum2(a,b):
    return a+b
    

In [12]:
sum2(2,3)

5

In [13]:
sum2(10,5)

15

In [28]:
def mul():
    a=1
    b=2
    return a*b

In [30]:
a=mul()
print(a)

2


In [31]:
def sum():
    return 5+a

In [32]:
sum()

7

In [17]:
def factorial(n):
    m=1
    for i in range(1,n+1):
        m=m*i
    print(m)


In [18]:
n=int(input())
factorial(n)

 4


24


In [11]:
factorial(10)

3628800

In [26]:
def forsum(l):
    s=0
    for i in l:
        s=s+i
    print(s)

In [27]:
m=list(map(int,input().split(' ')))
forsum(m)

 1 2 3 4 5


NameError: name 'a' is not defined

In [ ]:
# nested list
try and except
arrays
tuples
lambda functions
# dictonaries
# kwargs
strings and characters
# args



In [6]:
dict={"a":1,"b":2}
val=dict.items()
print(val)

dict_items([('a', 1), ('b', 2)])


In [10]:
def sum1(*args):
    print(args)

In [11]:
sum1(1,2,3,4)

(1, 2, 3, 4)


In [4]:
round(26.000000,2)

26.0

In [10]:
round(25,2)

25

In [19]:


def test(*args):
    s=0
    for i in args:
        s=s+i
    return s

In [22]:
test(1,2,3,4,5)

15

In [1]:
# list is a collection of non-homogenous elements
# nested list is a collection of list
# l=[1,2,3,4]
# nested_list=[[1,2,3,4],[5,6,7,8]]
k=list(map(int,input().split(' '))) 
a=0
for i in range(5):
    a=a+2
    print(a)
   
    
    

 5


2
4
6
8
10


In [34]:

for i in range(1,10):
    l=[]
    l.append(i)
    print(l)

[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]


In [38]:
nested_list=[[1,2,3,4],[5,6,7,8]]
# for i in nested_list:
#     print(i)
nested_list[0][2]

3

In [39]:
nested_list=[[1,2,3,4],[5,6,7,8]]
for i in nested_list:
    #i=[1,2,3,4]
    for j in i:
        print(j)
        

1
2
3
4
5
6
7
8


In [40]:
nested_list=[[1,2,3,4],[5,6,7,8]]
for i in range(len(nested_list)):
    for j in range(len(nested_list[i])):
        print(nested_list[i][j])

1
2
3
4
5
6
7
8


In [41]:
#dictionaries
# keys
# values
dictionary={'a':123,'b':456}

In [42]:
dictionary.get('a')

123

In [47]:

for i in dictionary:
    print(dictionary)

{'a': 123, 'b': 456}
{'a': 123, 'b': 456}


In [48]:
print(dictionary['a'])

123


In [49]:
employee_details={'12345678':['yeswanth',25],'3454323224':['pavan',25]}
employee_details.get('12345678')

['yeswanth', 25]

In [61]:
for i in employee_details.items():
    print(i)

('12345678', [123])
('3454323224', ['pavan', 25])
('2312121', 123)


In [56]:
employee_details.update({'12345678':['yesh',30]})

In [60]:
employee_details['12345678']=[123]

In [9]:
def test1(**kwargs):
    employee_details={'12345678':['yeswanth',25],'3454323224':['pavan',25]}
    for i in kwargs.values():
        print(employee_details[i])
test1(a='12345678')

['yeswanth', 25]


In [20]:
a='pavankumar'
print('.'.join(a))

p.a.v.a.n.k.u.m.a.r


In [18]:
a='pavan kumar'
print(a.split(' '))

['pavan', 'kumar']


In [22]:
a=['pavan', 'kumar']
print(' '.join(a))

pavan kumar


In [ ]:
Arrays
Arrays are same as lists
l=[]

array(type,[elements])

In [9]:
from array import *
arr=array('i',[1,2,3,4])

In [10]:
type(arr)

array.array

In [13]:
for i in arr:
    print(i)

1
2
3
4
5


In [12]:
arr.append(5)

In [14]:
arr[1:4]

array('i', [2, 3, 4])

In [67]:
import numpy as np
dict={'a':12345}
b=dict.keys()
a=np.array([1,2,dict])

In [68]:
print(type(a))

<class 'numpy.ndarray'>


In [69]:
for i in a:
    print(i)

1
2
{'a': 12345}


In [ ]:
int - float- string




In [70]:
arr=np.array(['pavan','kumar'])

In [72]:
for i in arr:
    print(i)

pavan
kumar


In [5]:
import numpy as np
# array=np.arange(start,end,stepsize)
array=np.arange(1,10,4)

In [86]:
for i in array:
    print(i)

1
5
9


In [78]:
print(array)

[1 2 3 4 5 6 7 8 9]


In [90]:
print(np.median(array))

5.0


In [91]:
a=np.arange(1,10)

In [93]:
b=a

In [94]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
b[0]=10

In [96]:
b

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [97]:
a

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [98]:
l=[1,2,3,4]

In [99]:
m=l

In [100]:
m

[1, 2, 3, 4]

In [101]:
m[0]=10

In [102]:
m

[10, 2, 3, 4]

In [103]:
l

[10, 2, 3, 4]

In [7]:
a=np.arange(1,10)

In [9]:
b=a.view()

In [11]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b[0]=11

In [17]:
b

array([11,  2,  3,  4,  5,  6,  7,  8,  9])

In [19]:
a

array([11,  2,  3,  4,  5,  6,  7,  8,  9])

In [21]:
a=np.arange(1,10)

In [23]:
b=a.copy()

In [25]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b[0]=12

In [31]:
b

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [33]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
n=int(input())
students=[]
dict={}
scores=[]
for i in range(n):
    name=input()
    score=float(input())
    scores.append(score)
    dict[name]=score
scores=sorted(set(scores))
for i in dict.keys():
    if dict[i]==scores[1]:
        students.append(i)
students=sorted(students)
for i in students:
    print(i)

 4
 hi
 2.3
 ji
 3.4
 ki
 4
 kii
 4.42


ji


In [12]:
n=int(input())
students=[]
scores=[]
m=[]
for i in range(n):
    name=input()
    score=float(input())
    scores.append(score)
    students.append([name,score])
scores=sorted(set(scores))
for i in students:
    if i[1]==scores[1]:
        m.append(i[0])
m=sorted(m)
for i in m:
    print(i)

 3
 a
 12
 b
 14
 c
 21


['b']


In [25]:
from array import *
import numpy as np


In [42]:
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [51]:
arr1=np.array([[1,23,4,5],[3,4,5,5],[3,4,5,6]])

In [50]:
print(sorted(arr1.flatten()))

[1, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 23]


In [46]:
arr=np.array([1,2,3,4,5,6])

In [47]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr1[0][1]

23

In [7]:
import numpy as np
a=np.matrix('1 2 3; 4 5 6; 7 8 9')

In [3]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(np.diagonal(a))

[1 5 9]


In [5]:
a=np.max(a)

In [6]:
a

9

In [8]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
a=np.matrix('1 2 3; 4 5 6; 7 8 9')
b=np.matrix('1 2 3; 4 5 6; 7 8 9')

In [14]:
print(a*b)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [1]:
String="Hello World"
l=list(String)
print(l)

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']


In [3]:
for i in String.split(' '):
    print(i)

Hello
World


In [5]:
print(String[0:3])

Hel


In [6]:
print(String*2)

Hello WorldHello World


In [9]:
a="pavan"
b="kumar"
print(a+" "+b)

pavan kumar


In [8]:
String="Hello World"
if 'Hello' in String:
    print('True')
else:
    print('false')

True


In [6]:
l=[1,2,4,5]
if 1 in l:
    print('true')

true


In [2]:
a='pavan'
b='pavan1'
if a<b:
    print('True')
else:
    print('false')

True


In [22]:
list=['apple','banana','ant']
list=sorted(list)
print(list)

['ant', 'apple', 'banana']


In [28]:
string="      Hello World "
print(string.strip())

Hello World


In [37]:
a='this is a book book'
b='book'
n=a.find(b,0,len(a))

In [38]:
print(n)

10


In [46]:
a='cdccdc'
b='cdc'
n=a.count(b,0,len(a))

In [36]:
print(n)

0


In [39]:
a='this is a book book'
b='book'
i=0
n=len(a)
while i<n:
    pos=a.find(b,i,n)
    if pos!=-1:
        print(pos)
        i=pos+1
    else:
        i=i+1


10
15


In [40]:
a='this is a book book'
b='book'
n=a.count(b,0,len(a))

In [47]:
print(n)

2


In [50]:
a='this is a book book'
b='pen'
c=a.replace('book',b)
print(c)

this is a pen pen


In [51]:
print(a.upper())

THIS IS A BOOK BOOK


In [64]:
a="Pavan"
print(a.istitle())

True


In [66]:
a=100000
print(f'{a} is my salary')

100000 is my salary


In [69]:
a="pavan"
type((a[0]))

str