In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
 np.__version__

'1.26.4'

In [8]:
list = [1,2,3,4]

In [10]:
type(list)

list

In [12]:
list

[1, 2, 3, 4]

CREATING ARRAYS USING NUMPY

In [15]:
n = np.array(list)

In [17]:
n

array([1, 2, 3, 4])

In [19]:
type(n)

numpy.ndarray

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(6.0)

array([0., 1., 2., 3., 4., 5.])

In the step function the second argument is need to be greater than the first arg

In [26]:
np.arange(26,60,2.6)

array([26. , 28.6, 31.2, 33.8, 36.4, 39. , 41.6, 44.2, 46.8, 49.4, 52. ,
       54.6, 57.2, 59.8])

np.arange()
np.zeros()
np.ones()

In [29]:
np.array((10,10))

array([10, 10])

In [33]:
k=np.arange(6)

In [35]:
k

array([0, 1, 2, 3, 4, 5])

In [37]:
n

array([1, 2, 3, 4])

In [ ]:
USING RANDINT AND RAND IN NUMPY
NEED USE RANDOM BEFORE USING RAND AND RANDOMINT

In [59]:
l=np.random.rand(6,6)

In [61]:
l

array([[0.80510313, 0.02700567, 0.25797794, 0.68781354, 0.40875803,
        0.15885566],
       [0.37924593, 0.08121331, 0.37396172, 0.62116655, 0.52074595,
        0.18659427],
       [0.2142683 , 0.80839476, 0.33649963, 0.47668611, 0.87825265,
        0.65676149],
       [0.24335486, 0.46111411, 0.85735623, 0.09762828, 0.15490226,
        0.99686798],
       [0.88506053, 0.70427467, 0.6455347 , 0.25076741, 0.81799647,
        0.52883987],
       [0.99810222, 0.79350574, 0.60125869, 0.67658178, 0.61815128,
        0.54175091]])

In [63]:
s=np.random.randint(6,26,(6,6))

In [66]:
s

array([[12, 16, 23, 15, 10, 12],
       [20, 13, 20, 22, 10, 23],
       [16, 22, 19, 14, 25, 19],
       [13, 16, 23, 16,  6, 25],
       [12, 13, 14,  9, 16, 12],
       [22, 24, 22, 19, 12, 15]])

SLICING OPERATION IN NUMPYS

In [71]:
s

array([[12, 16, 23, 15, 10, 12],
       [20, 13, 20, 22, 10, 23],
       [16, 22, 19, 14, 25, 19],
       [13, 16, 23, 16,  6, 25],
       [12, 13, 14,  9, 16, 12],
       [22, 24, 22, 19, 12, 15]])

In [73]:
s[0:2]

array([[12, 16, 23, 15, 10, 12],
       [20, 13, 20, 22, 10, 23]])

ARRAY REVERSE IN NUMPY

In [81]:
s[::-1]

array([[22, 24, 22, 19, 12, 15],
       [12, 13, 14,  9, 16, 12],
       [13, 16, 23, 16,  6, 25],
       [16, 22, 19, 14, 25, 19],
       [20, 13, 20, 22, 10, 23],
       [12, 16, 23, 15, 10, 12]])

using max(), min(), mean()
To use medianneed to import numpy like from numpy import *

In [108]:
s.max()

25

In [110]:
s.min()

6

In [112]:
s.mean()

16.666666666666668

In [114]:
from numpy import *

In [116]:
median(s)

16.0

In [118]:
n

array([1, 2, 3, 4])

In [120]:
n.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [122]:
n.reshape(1,4)

array([[1, 2, 3, 4]])

In [124]:
n.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [167]:
ls=np.arange(30)

In [169]:
ls

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [171]:
ls

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [179]:
ls.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

indexing in numpy

In [270]:
kls=np.arange(26,126).reshape(10,10)

In [272]:
kls

array([[ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50,  51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120, 121, 122, 123, 124, 125]])

In [274]:
row=6
col=26

In [276]:
col

26

In [278]:
row

6

In [280]:
kls[row:col]

array([[ 86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120, 121, 122, 123, 124, 125]])

In [282]:
kls[row:]

array([[ 86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120, 121, 122, 123, 124, 125]])

In [284]:
kls[:row]

array([[26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80, 81, 82, 83, 84, 85]])

In [286]:
kls[:col]

array([[ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50,  51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120, 121, 122, 123, 124, 125]])

In [288]:
kls[col:]

array([], shape=(0, 10), dtype=int64)

In [290]:
kls[:,row]

array([ 32,  42,  52,  62,  72,  82,  92, 102, 112, 122])

In [292]:
kls[row,:]

array([86, 87, 88, 89, 90, 91, 92, 93, 94, 95])

In [294]:
kls[:,col]

IndexError: index 26 is out of bounds for axis 1 with size 10

In [218]:
kls[col,:]

IndexError: index 26 is out of bounds for axis 0 with size 10

In [296]:
kls[1:2,2:1]

array([], shape=(1, 0), dtype=int64)

In [298]:
kls

array([[ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50,  51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120, 121, 122, 123, 124, 125]])

In [300]:
kls[3:6,5:8]

array([[61, 62, 63],
       [71, 72, 73],
       [81, 82, 83]])

masking in numpy

In [303]:
kls<32

array([[ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [305]:
kls>32

array([[False, False, False, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [308]:
kls<60

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [310]:
kls<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [312]:
kls

array([[ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50,  51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120, 121, 122, 123, 124, 125]])

In [316]:
y=kls[kls<26]

In [319]:
y

array([], dtype=int64)

In [321]:
y=kls[kls>26]

In [323]:
y

array([ 27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125])

In [327]:
y=kls[kls<32]

In [329]:
y

array([26, 27, 28, 29, 30, 31])

In [333]:
y=kls[kls>32]

In [335]:
y

array([ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
        46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
        59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
       111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
       124, 125])